-- Migration: Add enhanced pricing fields to activities and meals

ALTER TABLE activities 
ADD COLUMN IF NOT EXISTS total_price DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS deposit_amount DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS prepayment_required BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pay_on_arrival BOOLEAN DEFAULT FALSE;

ALTER TABLE meals
ADD COLUMN IF NOT EXISTS total_price DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS deposit_amount DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS prepayment_required BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pay_on_arrival BOOLEAN DEFAULT FALSE;
